Repository elice-study-3rd/country-search-app, pull requests merged in 2023-10, with the labels that each got.

#2 (API) 국가 정보를 반환하는 함수
  src/api/fetch.js
Labels: API

#11 메인 페이지 UI 구현
  .github/issue-✅기능-요구사항.md
  package-lock.json
  package.json
  src/Header.css
  src/Header.js
  src/assets/default/no_image.png
  src/components/CountryCard.jsx
  src/index.js
  src/pages/Main.jsx
  src/styles/CountryCard.css
  src/styles/Main.css
Labels: feat

#6 (API) 국가 정보를 반환하는 클래스로 변경 및 로컬 스토리지 분기 추가
  src/api/fetch.js
Labels: API

#14 (API) Fetcher 클래스에 오름차순/내림차순 정렬 함수 추가
  src/api/fetch.js
Labels: feat, API

#17 로딩 및 에러 페이지 구현
  src/api/fetch.js
  src/components/Error.jsx
  src/components/skeleton/CountryCardSkeleton.jsx
  src/constants/error.js
  src/pages/Main.jsx
  src/styles/CountryCard.css
  src/styles/Error.css
  src/styles/skeleton/Skeleton.css
Labels: feat

#23 검색 컴포넌트와 헤더 컴포넌트를 메인 컴포넌트와 결합하기
  package-lock.json
  package.json
  public/index.html
  src/assets/default/no_image.png
  src/assets/default/no_result.png
  src/components/CountryCard.jsx
  src/components/Header.jsx
  src/components/Search.jsx
  src/components/skeleton/CountryCardSkeleton.jsx
  src/pages/Main.jsx
  src/styles/CountryCard.css
  src/styles/Main.css
  src/styles/Search.css
  src/styles/skeleton/Skeleton.css
Labels: feat

#28 keyword를 보내는 방식 변경 및 region으로 검색 기능 추가
  src/components/CountryModal.js
  src/styles/CountryModal.css
Labels: feat

#26 (ROUTER) URL path 값을 받아와서 렌더링할 데이터를 반환하는 함수 추가
  src/pages/Main.jsx
  src/router/router.js
Labels: feat
